apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-revisit
  labels:
    app: kubernetes-revisit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-revisit
  template:
    metadata:
      labels:
        app: kubernetes-revisit
    spec:
      containers:
      - name: kubernetes-revisit
        image: kubernetes-revisit:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080