apiVersion: v1
kind: Service
metadata:
  name: kubernetes-revisit-service
  labels:
    app: kubernetes-revisit
spec:
  type: NodePort
  selector:
    app: kubernetes-revisit
  ports:
   - protocol: TCP
     port: 8080
     targetPort: 8080
     nodePort: 30080
     name: http
